api_platform:
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    patch_formats:
        json: ["application/merge-patch+json"]
    swagger:
        versions: [3]
        api_keys:
            Header:
                name: Authorization
                type: header
            Query:
                name: apikey
                type: query
    defaults:
        formats:
            - "json"
            - "jsonld"

        pagination_items_per_page: 15
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 30

    collection:
        pagination:
            items_per_page_parameter_name: items

    show_webby: false
